/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogAnatomyOfADeceptiveDeveloperAttackRouteImport } from './routes/blog.anatomy-of-a-deceptive-developer-attack'

const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAnatomyOfADeceptiveDeveloperAttackRoute =
  BlogAnatomyOfADeceptiveDeveloperAttackRouteImport.update({
    id: '/blog/anatomy-of-a-deceptive-developer-attack',
    path: '/blog/anatomy-of-a-deceptive-developer-attack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/playbook': typeof PlaybookRoute
  '/blog/anatomy-of-a-deceptive-developer-attack': typeof BlogAnatomyOfADeceptiveDeveloperAttackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/playbook': typeof PlaybookRoute
  '/blog/anatomy-of-a-deceptive-developer-attack': typeof BlogAnatomyOfADeceptiveDeveloperAttackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/playbook': typeof PlaybookRoute
  '/blog/anatomy-of-a-deceptive-developer-attack': typeof BlogAnatomyOfADeceptiveDeveloperAttackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/playbook' | '/blog/anatomy-of-a-deceptive-developer-attack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/playbook' | '/blog/anatomy-of-a-deceptive-developer-attack'
  id:
    | '__root__'
    | '/'
    | '/playbook'
    | '/blog/anatomy-of-a-deceptive-developer-attack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlaybookRoute: typeof PlaybookRoute
  BlogAnatomyOfADeceptiveDeveloperAttackRoute: typeof BlogAnatomyOfADeceptiveDeveloperAttackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/anatomy-of-a-deceptive-developer-attack': {
      id: '/blog/anatomy-of-a-deceptive-developer-attack'
      path: '/blog/anatomy-of-a-deceptive-developer-attack'
      fullPath: '/blog/anatomy-of-a-deceptive-developer-attack'
      preLoaderRoute: typeof BlogAnatomyOfADeceptiveDeveloperAttackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlaybookRoute: PlaybookRoute,
  BlogAnatomyOfADeceptiveDeveloperAttackRoute:
    BlogAnatomyOfADeceptiveDeveloperAttackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
