/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsExampleSummaryRouteImport } from './routes/reports.example-summary'
import { Route as ReportsExampleScaRouteImport } from './routes/reports.example-sca'
import { Route as ReportsExamplePayloadAnalysisRouteImport } from './routes/reports.example-payload-analysis'
import { Route as BlogAnatomyOfADeceptiveDeveloperAttackRouteImport } from './routes/blog.anatomy-of-a-deceptive-developer-attack'

const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExampleSummaryRoute = ReportsExampleSummaryRouteImport.update({
  id: '/reports/example-summary',
  path: '/reports/example-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExampleScaRoute = ReportsExampleScaRouteImport.update({
  id: '/reports/example-sca',
  path: '/reports/example-sca',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsExamplePayloadAnalysisRoute =
  ReportsExamplePayloadAnalysisRouteImport.update({
    id: '/reports/example-payload-analysis',
    path: '/reports/example-payload-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogAnatomyOfADeceptiveDeveloperAttackRoute =
  BlogAnatomyOfADeceptiveDeveloperAttackRouteImport.update({
    id: '/blog/anatomy-of-a-deceptive-developer-attack',
    path: '/blog/anatomy-of-a-deceptive-developer-attack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/playbook': typeof PlaybookRoute
  '/blog/anatomy-of-a-deceptive-developer-attack': typeof BlogAnatomyOfADeceptiveDeveloperAttackRoute
  '/reports/example-payload-analysis': typeof ReportsExamplePayloadAnalysisRoute
  '/reports/example-sca': typeof ReportsExampleScaRoute
  '/reports/example-summary': typeof ReportsExampleSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/playbook': typeof PlaybookRoute
  '/blog/anatomy-of-a-deceptive-developer-attack': typeof BlogAnatomyOfADeceptiveDeveloperAttackRoute
  '/reports/example-payload-analysis': typeof ReportsExamplePayloadAnalysisRoute
  '/reports/example-sca': typeof ReportsExampleScaRoute
  '/reports/example-summary': typeof ReportsExampleSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/playbook': typeof PlaybookRoute
  '/blog/anatomy-of-a-deceptive-developer-attack': typeof BlogAnatomyOfADeceptiveDeveloperAttackRoute
  '/reports/example-payload-analysis': typeof ReportsExamplePayloadAnalysisRoute
  '/reports/example-sca': typeof ReportsExampleScaRoute
  '/reports/example-summary': typeof ReportsExampleSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commands'
    | '/playbook'
    | '/blog/anatomy-of-a-deceptive-developer-attack'
    | '/reports/example-payload-analysis'
    | '/reports/example-sca'
    | '/reports/example-summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commands'
    | '/playbook'
    | '/blog/anatomy-of-a-deceptive-developer-attack'
    | '/reports/example-payload-analysis'
    | '/reports/example-sca'
    | '/reports/example-summary'
  id:
    | '__root__'
    | '/'
    | '/commands'
    | '/playbook'
    | '/blog/anatomy-of-a-deceptive-developer-attack'
    | '/reports/example-payload-analysis'
    | '/reports/example-sca'
    | '/reports/example-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandsRoute: typeof CommandsRoute
  PlaybookRoute: typeof PlaybookRoute
  BlogAnatomyOfADeceptiveDeveloperAttackRoute: typeof BlogAnatomyOfADeceptiveDeveloperAttackRoute
  ReportsExamplePayloadAnalysisRoute: typeof ReportsExamplePayloadAnalysisRoute
  ReportsExampleScaRoute: typeof ReportsExampleScaRoute
  ReportsExampleSummaryRoute: typeof ReportsExampleSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/example-summary': {
      id: '/reports/example-summary'
      path: '/reports/example-summary'
      fullPath: '/reports/example-summary'
      preLoaderRoute: typeof ReportsExampleSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/example-sca': {
      id: '/reports/example-sca'
      path: '/reports/example-sca'
      fullPath: '/reports/example-sca'
      preLoaderRoute: typeof ReportsExampleScaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/example-payload-analysis': {
      id: '/reports/example-payload-analysis'
      path: '/reports/example-payload-analysis'
      fullPath: '/reports/example-payload-analysis'
      preLoaderRoute: typeof ReportsExamplePayloadAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/anatomy-of-a-deceptive-developer-attack': {
      id: '/blog/anatomy-of-a-deceptive-developer-attack'
      path: '/blog/anatomy-of-a-deceptive-developer-attack'
      fullPath: '/blog/anatomy-of-a-deceptive-developer-attack'
      preLoaderRoute: typeof BlogAnatomyOfADeceptiveDeveloperAttackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandsRoute: CommandsRoute,
  PlaybookRoute: PlaybookRoute,
  BlogAnatomyOfADeceptiveDeveloperAttackRoute:
    BlogAnatomyOfADeceptiveDeveloperAttackRoute,
  ReportsExamplePayloadAnalysisRoute: ReportsExamplePayloadAnalysisRoute,
  ReportsExampleScaRoute: ReportsExampleScaRoute,
  ReportsExampleSummaryRoute: ReportsExampleSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
